columns:
- Date	
- Hour	
- Temperature	
- Humidity	
- Wind 
- speed	
- Visibility	
- Dew point temperature	
- Solar Radiation	Rainfall	
- Snowfall	
- Seasons	
- Holiday	
- Functioning Day

target column:
- Rented Bike Count	